filebeat.prospectors:
- input_type: log
  paths:
    - /var/log/host/messages*
    - /var/log/host/syslog*
  exclude_files: [".gz$"]
  multiline:
    pattern: "^\\s"
    match: after
output.logstash:
  hosts: ["15.15.1.2:5044"]
